service: authorizer-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  httpApi:
    cors:
      allowedOrigins: '*'
      allowedHeaders: '*'
      allowedMethods: '*'
  lambdaHashingVersion: 20201221

functions:
  basicAuthorizer:
    handler: ./src/handler.basicAuthorizer
    events:
      - httpApi:
          path: basicAuthorizer
          method: get
          description: 'Authorization'
          responseData: 
            200:
              description: 'Successful response'
            400:
              description: 'Bad request'
            401:
              description: 'Unauthorized'
            403:
              description: 'Forbidden'
            500:
              description: 'Server error'

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    platform: 'node'
    packager: npm
    packagePath: package.json
  autoswagger:
    title: 'Import service API'
    apiType: 'httpApi'
    generateSwaggerOnDeploy: true
    swaggerPath: 'swagger'
    typefiles: ['./src/interfaces/product.interface.ts']
    basePath: '/'
    schemes: ['https']

plugins:
  # - serverless-plugin-typescript
  - serverless-esbuild
  - serverless-auto-swagger
  - serverless-offline
  - serverless-dotenv-plugin
